# Script para criar repositório no GitHub e fazer push do código
Write-Host "Este script irá ajudá-lo a criar um repositório no GitHub e fazer push do seu código."
Write-Host "Siga as instruções abaixo:"
Write-Host ""
Write-Host "1. Acesse https://github.com/login e faça login na sua conta do GitHub"
Write-Host "2. Acesse https://github.com/new para criar um novo repositório"
Write-Host "3. Preencha as informações do repositório:"
Write-Host "   - Nome do repositório: sergio-imports--para-loja"
Write-Host "   - Descrição: (opcional)"
Write-Host "   - Público ou Privado: (sua escolha)"
Write-Host "   - NÃO marque nenhuma das opções de inicialização (README, .gitignore, licença)"
Write-Host "4. Clique em 'Create repository'"
Write-Host ""
Write-Host "5. Após criar o repositório, execute os seguintes comandos no terminal:"
Write-Host "   git remote add origin https://github.com/SEU_USUARIO/sergio-imports--para-loja.git"
Write-Host "   git branch -M main"
Write-Host "   git push -u origin main"
Write-Host ""
Write-Host "Substitua SEU_USUARIO pelo seu nome de usuário do GitHub."